version: 2
updates:
- package-ecosystem: "nuget"
  directory: "MumbleServerStatsd/src/MumbleServerStatsd/MumbleServerStatsd.csproj"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - corenting
