name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime-identifier: [ "win-x64", "win-arm64", "linux-x64", "linux-musl-x64", "linux-arm64", "linux-arm"]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build app
      run: make release
      env:
        RUNTIME_IDENTIFIER: ${{ matrix.runtime-identifier }}
