name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build (win-x64)
      run: make release
      env:
        RUNTIME_IDENTIFIER: win-x64
    - name: Build (win-arm64)
      run: make release
      env:
        RUNTIME_IDENTIFIER: win-arm64
    - name: Build (linux-x64)
      run: make release
    - name: Build (linux-musl-x64)
      run: make release
      env:
        RUNTIME_IDENTIFIER: linux-musl-x64
    - name: Build (linux-arm64)
      run: make release
      env:
        RUNTIME_IDENTIFIER: linux-arm64
    - name: Build (linux-arm)
      run: make release
      env:
        RUNTIME_IDENTIFIER: linux-arm